Feature - Button group
gsoft-inc/ov-igloo-ui pull request #101
Opened 2022-04-01 15:13 UTC by franckgaudin

<img width="1877" alt="Capture d’écran, le 2022-04-01 à 11 13 17" src="https://user-images.githubusercontent.com/2379339/161291925-715fea34-474d-4194-bd26-6a1805c68865.png">

2022-04-01 15:56 UTC, ofrogon requested changes

2022-04-01 15:56 UTC, ofrogon commented on packages/ButtonGroup/package.json
> +  "styles": "dist/button-group.js",
style devrait être un .css

2022-04-01 15:56 UTC, ofrogon commented on packages/ButtonGroup/src/ButtonGroup.tsx
> +export { ButtonGroupItem as Item };
J'accroche un peu sur le fait, que ce que contient un `ButtonGroup` ce soit des `Item`, mais pas des `Button`.

2022-04-01 15:56 UTC, ofrogon commented on packages/ButtonGroup/src/ButtonGroupItem.tsx
> +  dataTest?: string;
Il manque le "c" de function
Il y a des "." de trop en fin de phrase

2022-04-01 15:56 UTC, ofrogon commented on packages/ButtonGroup/src/ButtonGroup.tsx
> +  /** React node child representing the button content text or icon. */
Point de trop en fin de phrase

2022-04-01 15:56 UTC, ofrogon commented on packages/ButtonGroup/src/ButtonGroup.tsx
> +  /** React node child representing the button content text or icon. */
Inverse aussi "child" et "node", c'est plus exacte côté syntaxique

2022-04-01 15:56 UTC, ofrogon commented on packages/ButtonGroup/src/ButtonGroupItem.tsx
> +  /** Whether or not the button is active. */
Tu utilise le terme "button" selon le choix de comment on nomme "Item", il va p-e falloir normaliser le terme ici.

2022-04-01 15:56 UTC, ofrogon commented on typings/icons.d.ts
> +  export default Icon;
Ha! Super, c'est tellement plus propre que d'avoir à ajouter un icône à la liste à chaque fois. 👏

2022-04-01 15:56 UTC, ofrogon commented on packages/ButtonGroup/src/button-group.scss
> +  --ids-button-group-padding: 0 #{$space-3};
cette variable n'est jamais utilisée

2022-04-01 15:56 UTC, ofrogon commented on packages/ButtonGroup/src/ButtonGroup.tsx
> +export { ButtonGroupItem as Item };
Si on ne veut pas associer ce bouton au component `Button` on pourrait aussi juste utiliser le nom `ButtonGroupItem` au lieu de l'alias

2022-04-04 14:25 UTC, franckgaudin commented on packages/ButtonGroup/src/ButtonGroup.tsx
> +export { ButtonGroupItem as Item };
J'ai remplacé le nom `Item` pour `ButtonItem` car je trouve que `ButtonGroupItem` c'est vraiment long.

2022-04-04 14:42 UTC, ofrogon approved these changes

2022-04-05 13:22 UTC, syvuo commented on packages/ButtonGroup/src/ButtonGroup.tsx
> +  const { children, compact = false, small = false, dataTest } = props;
`compact `et small `devraient `déjà être false par défaut non?

2022-04-05 23:56 UTC, merged