Feature/button qa
gsoft-inc/ov-igloo-ui pull request #22
Opened 2021-12-13 16:35 UTC by ofrogon

- New: Premium Button color changed
- New: Focus effect preview in Storybook
- New: When text is too long for the button, the end is replaced by ellipses
- Fix: Active button should not have `:hover` effects
- Fix: `lint:style` and `fix:style` commands on Windows
- Bonus: Add `lint:all` and `fix:all` to run linting and fix linting in bulk

2021-12-13 18:51 UTC, franckgaudin requested changes

2021-12-13 18:51 UTC, franckgaudin commented on packages/Button/src/Button.tsx
> +          <span>{children}</span>
Il serait mieux de supprimer la condition `showOnlyIconOnMobile` et d'utiliser dans tous les cas de figure 
`<span className="ids-btn__label">{children}</span>`

2021-12-13 18:51 UTC, franckgaudin commented on packages/Button/src/button.scss
> +  --ids-btn-text-premium-disabled: var(--grey-600);
dans le Figma la couleur est a --grey-500
```suggestion
  --ids-btn-text-premium-disabled: var(--grey-500);
```

2021-12-13 18:51 UTC, franckgaudin commented on packages/Button/src/button.scss
> +  --ids-btn-outline-premium: var(--electric-blue-500);
cette variable n'est pas nécessaire car tous le bouton utilise la même couleur de focus

2021-12-13 18:51 UTC, franckgaudin commented on packages/Button/src/button.scss
> +.ids-btn:focus:not(:focus-visible)::after,
Ces déclaration empêche l'affichage du focus lors de l'utilisation de `.focus` dans storybook

<img width="1326" alt="Capture d’écran, le 2021-12-13 à 13 48 41" src="https://user-images.githubusercontent.com/2379339/145870473-da5874dc-3b17-45a6-bb9f-f2055d6d14ad.png">
.

2021-12-13 18:51 UTC, franckgaudin commented on packages/Button/src/button.scss
> +.ids-btn--premium:focus:not(.ids-btn--loading),
Tu ne devrais pas a avoir a déclarer le focus uniquement pour l'apparence `premium` il devrait être commun a tous les boutons

2021-12-13 20:45 UTC, ofrogon commented on packages/Button/src/Button.tsx
> +          <span>{children}</span>
Si je fais ça, dès que l'on est en mobile, le text disparait dans tous les boutons.

## \<span className="ids-btn__label">

![image](https://user-images.githubusercontent.com/4323800/145885810-7c738057-b009-4c5e-8502-49dcdeadf594.png)

## \<span>

![image](https://user-images.githubusercontent.com/4323800/145885968-90f960f8-4ac7-48bb-9536-545309a652f9.png)

2021-12-13 20:56 UTC, ofrogon commented on packages/Button/src/button.scss
> +  --ids-btn-text-premium-disabled: var(--grey-600);
Corrigé dans commit ce5bc53

2021-12-13 20:57 UTC, ofrogon commented on packages/Button/src/button.scss
> +  --ids-btn-outline-premium: var(--electric-blue-500);
Corrigé dans commit ce5bc53

2021-12-13 20:57 UTC, ofrogon commented on packages/Button/src/button.scss
> +.ids-btn:focus:not(:focus-visible)::after,
Corrigé dans commit ce5bc53

2021-12-13 20:58 UTC, ofrogon commented on packages/Button/src/button.scss
> +.ids-btn--premium:focus:not(.ids-btn--loading),
Ha, ok, je pesais que seulement `Primary` se retrouvait avec la focus de cette façon. C'est corrigé dans le commit ce5bc53

2021-12-13 21:00 UTC, ofrogon commented on packages/Button/src/Button.tsx
> +          <span>{children}</span>
Aussi, j'ai besoin du `span` pour que les `ellipses` fonctionne sur le texte (selon mes recherches, il faut un élément enfant avec un `min-width` de configuré quand le conteneur est un `flex`).

2021-12-15 15:32 UTC, franckgaudin commented on packages/Button/src/button.scss
>  .ids-btn::after {
La stratégie qui était utilisé pour afficher le focus a changé de ce fait tu peux supprimer toutes les référence au `::after` et remplacer par:

``` 
.ids-btn:focus,
.ids-btn.focus {
  box-shadow: var(--focus);
}
```

2021-12-15 15:32 UTC, franckgaudin commented on packages/Button/src/button.scss
> +.ids-btn:focus:not(.ids-btn--loading),
Tu peux ajouter ces déclarations a la suite de  `.ids-btn.focus, .ids-btn:focus, ....`

2021-12-15 15:32 UTC, franckgaudin commented on packages/Button/package.json
>  {
Tu peux upgrade la version des `@igloo-ui/tokens` à la version `1.1.0`

2021-12-15 15:32 UTC, franckgaudin commented on packages/Button/src/button.scss
> +.ids-btn:focus::after,
A supprimer
```suggestion
```

2021-12-15 15:32 UTC, franckgaudin commented on packages/Button/src/button.scss
> +.ids-btn.focus::after {
idem
```suggestion
{
```

2021-12-15 15:32 UTC, franckgaudin commented on packages/Button/src/button.scss
> +  outline: 2px solid var(--ids-btn-outline);
pour garder une cohérence avec les autres composant on affiche l'effet de focus avec la déclaration `box-shadow`, tu peux donc supprimer les outline

2021-12-15 20:02 UTC, ofrogon commented on packages/Button/package.json
> +  "version": "0.1.3",
Oui, mais suite à notre conversation, j'ai compris comment ça incrémente automatiquement.

2021-12-15 20:48 UTC, ofrogon commented on packages/Button/src/button.scss
> +.ids-btn:focus:not(.ids-btn--loading),
Je n'ai pas trop compris ton commentaire ici, mais j'ai changé cette section dans le dernier commit (b1cceed) peut-être que j'ai corrigé ceci par la bande.

2022-01-10 16:23 UTC, franckgaudin commented on packages/Button/src/button.scss
> +
Afin de retirer l'effet de focus lors du click sur le bouton ajout ce bout de code 
```suggestion
.ids-btn:focus:not(:focus-visible) {
  box-shadow: none;
}
```

2022-01-10 19:11 UTC, franckgaudin submitted a review, later dismissed

2022-01-11 14:58 UTC, syvuo approved these changes

2022-01-11 16:00 UTC, franckgaudin approved these changes

2022-01-11 16:02 UTC, merged