Feature/tooltip
gsoft-inc/ov-igloo-ui pull request #25
Opened 2022-01-11 16:35 UTC by ofrogon

Nouveau component : `Tooltip`

Caractéristiques:
 - Thème sombre et claire.
 - Plusieurs positions (Haut ; Bas ; Gauche ; Droite).
 - Supporte les REACT Components.
 - Logique pour afficher à la position opposée s'il manque d'espace à la position par défaut.
 - Largeur maximale configurable.
 - Option d'afficher une flèche ou non.

![2FE1E4D7-5B7D-4803-8898-AC2F562EC5C8](https://user-images.githubusercontent.com/4323800/148982596-1cbbe907-a5d7-419b-96b1-3695d402201c.GIF)

2022-01-13 18:26 UTC, syvuo reviewed
Est-ce intentionel d'avoir commit .idea?

2022-01-13 18:34 UTC, ofrogon commented
Oups, non, ça va pas la.

2022-01-14 19:14 UTC, syvuo approved these changes

2022-01-14 20:12 UTC, franckgaudin requested changes

2022-01-14 20:12 UTC, franckgaudin commented on .stylelintrc.json
>    "ignoreFiles": ["**/dist/*.css", "website/**/*.scss"],
Il te faut ajouter cette option autrement le lint va fail. 
```
"website/**/*.scss"
```

2022-01-14 20:12 UTC, franckgaudin commented on packages/Tooltip/src/tooltip.scss
> +  --ids-tooltip-font-size: 12px;
Utilise le token `$font-size-2` pour la taille de font

2022-01-14 20:12 UTC, franckgaudin commented on packages/Tooltip/src/tooltip.scss
> +  --ids-tooltip-spacing: 8px;
Utilise ce token `$space-2` pour le spacing

2022-01-14 20:12 UTC, franckgaudin commented on packages/Tooltip/src/tooltip.scss
> +    font-size: var(--ids-tooltip-font-size);
Je ne vois pas cette class dans le fichier Tooltip.tsx

2022-01-14 20:12 UTC, franckgaudin commented on packages/Tooltip/src/tooltip.scss
> +  &-dark {
on va le remplacer par le light

2022-01-14 20:12 UTC, franckgaudin commented on packages/Tooltip/src/tooltip.scss
> +  --ids-tooltip-text: var(--grey-800);
Comme le tooltip de base sera dark on va changer la var pour `var(--samoyed)`

2022-01-14 20:12 UTC, franckgaudin commented on packages/Tooltip/src/tooltip.scss
> +  --ids-tooltip-background: var(--samoyed);
var(--grey-800)

2022-01-14 20:12 UTC, franckgaudin commented on packages/Tooltip/src/tooltip.scss
> +  box-shadow: var(--ids-tooltip-shadow);
il faut retirer le shadow

2022-01-14 20:39 UTC, ofrogon commented on .eslintrc.json
> +    "linebreak-style": "off",
C'est pour désactiver la vérification qui s'assure que la fin de ligne est du CR/LF/CRLF.

Mais au final, Prettier venait aussi chialer sur les mêmes "erreur" après... j'ai fini par trouver comment corriger Prettier après, mais j'avais déjà contourner le problème par le `.editorconfig`.

Ce que ça cause c'est que dès que l'on change de branche dans Git, à chaque fois les fichiers se retrouvent en CRLF si, lors de l'installation de Git Windows on a laissé:
![image](https://user-images.githubusercontent.com/4323800/149580465-dd1d8499-ee39-4df2-8b45-fd162bc51c0a.png)

Je vais profiter qu'il faut que je fasse certains changement suite a ta revue pour désactiver la règle dans Prettier aussi.

2022-01-14 22:02 UTC, ofrogon commented on .eslintrc.json
> +    "linebreak-style": "off",
Finalement dans Prettier ça ne fonctionne pas, je vais modifier le `.gitattributes`.

Comme ça, le flow de travail devrait être couvert:
- Création/Éditer/Sauvegarde -> .editorconfig
- Tous ce qui est Git -> .gitattributes

Ça me dépasse tellement qu'en 2021 les fin de lignes ce soit encore problématique 🤯

2022-01-17 18:35 UTC, franckgaudin commented on packages/Tooltip/package.json
> +    "Franck franck.gaudin@gsoft.com"
Tu peux indiquer comme contributeur ;)

2022-01-17 18:35 UTC, franckgaudin commented on packages/Tooltip/src/Tooltip.tsx
> +  arrowVisible?: boolean;
```suggestion

```

2022-01-17 18:35 UTC, franckgaudin commented on packages/Tooltip/src/Tooltip.tsx
> +  children: string | React.ReactNode;
```suggestion
  children: React.ReactNode;
```

2022-01-17 18:35 UTC, franckgaudin commented on packages/Tooltip/src/Tooltip.tsx
> +    'ids-tooltip-light': appearance === 'light',
On se base sur la méthodologie BEM pour la nomenclature des className, tu peux le remplacer par:
```suggestion
    'ids-tooltip--light': appearance === 'light',
```

2022-01-17 20:09 UTC, franckgaudin commented on packages/Tooltip/src/Tooltip.tsx
> +          classNames('ids-tooltip', tooltipClassName, {
👆

2022-01-17 20:34 UTC, franckgaudin approved these changes

2022-01-17 21:10 UTC, syvuo approved these changes

2022-01-17 21:15 UTC, merged