Feature link
gsoft-inc/ov-igloo-ui pull request #63
Opened 2022-02-11 21:23 UTC by franckgaudin

# `Link` component

### Component API

| name       | description                                          |
| ---------- | ---------------------------------------------------- |
| appearance       | link appearance `primary, secondary, premium, ghost, danger`                         |
| size | Changes the size of link, giving more or less padding <br/> `small, medium` |
| iconLeading | Icon to display to the left of link content |
| iconTrailing | Icon to display to the right of link content |
| children | the content to display inside the link |
| active | sets the link in an active state |
| disabled | disabled the link, the user cannot click on them | 
| dataTest | add a data-test tag for automated tests |
| showOnlyIconOnMobile | display only the icon in mobile |
| className | add a specific class to the link |
| intercomTarget | add a data-intercom-target with unique id to link a components to a Product Tour step |

2022-02-14 16:21 UTC, ofrogon requested changes

2022-02-14 16:21 UTC, ofrogon commented on packages/Link/src/Link.tsx
> +   *  not to be used with an achore children
Cherche tu à dire `anchor` ⚓  ou `ashore` 🏖️ ?

2022-02-14 16:21 UTC, ofrogon commented on packages/Link/src/link.scss
> +  }
`cursor: pointer` est répété dans le sélecteur juste après, tu peux enlever celui-ci.

2022-02-14 16:41 UTC, syvuo commented on packages/Link/src/link.scss
> +  --ids-link-icon-color: currencolor;
Typo? currentColor?

2022-02-15 19:09 UTC, franckgaudin commented on packages/Link/.npmignore
> +src/
c'est voulu oui car ce fichier empêche de publier le dossier `src/` sur npm

2022-02-15 19:18 UTC, ofrogon commented on packages/Link/.npmignore
> +src/
Haha, en lisant vite j'avais vue `.gitignore`, c'est ça qui m'était étrange.

2022-02-15 19:36 UTC, franckgaudin commented on packages/Link/src/Link.stories.tsx
> +      <a href="#">Gost</a>
done

2022-02-15 19:36 UTC, franckgaudin commented on packages/Link/src/Link.tsx
> +   *  not to be used with an achore children
Oups

2022-02-15 21:04 UTC, ofrogon approved these changes

2022-02-17 13:57 UTC, syvuo submitted a review, later dismissed

2022-02-22 14:01 UTC, SamuelCharest commented on packages/Link/src/Link.tsx
> +import * as React from 'react';
Je suis surpris de voir que le component Link ne gère pas la redirection que ce soit interne ou externe, ce components semble seulement être un wrapper de style.

J'aurais penser avoir la logique de redirection dans ce components pour ne pas avoir un overhead d'importer <Link /> de react-router-dom en plus du Link de Igloo lorsque je désire utiliser un lien.

De plus, d'avoir un overide de nom, ce qu'il va propablement arrivé dans portal, nous allons créer un autre component générique par dessus celui de igloo pour wrapper cette logique et utilisé ce nouveau component générique. Ceci brise un peu le purpose de créer le design system Igloo

2022-02-22 15:08 UTC, franckgaudin commented on packages/Link/src/Link.tsx
> +import * as React from 'react';
Ton analyse du composant est juste c'est bien un wrapper de style. 
Nous avons extraire la logique du router pour laisser le plus de flexibilité a l'utilisation d'Igloo car aujourd'hui il est principalement utiliser par portal mais ça ne sera pas toujours le cas. 

En ce qui concerne l'overide de nom, on peut arranger ça en le nommant par exemple `TextLink`.

2022-02-22 15:54 UTC, SamuelCharest commented on packages/Link/src/Link.tsx
> +import * as React from 'react';
A voir si vous voulez le renommer TextLink si ca viens en conflit avec un ButtonLink si vous le créer. :)

2022-02-22 18:34 UTC, ofrogon approved these changes

2022-02-24 20:29 UTC, jpineault submitted a review, later dismissed

2022-02-24 20:38 UTC, ofrogon commented on packages/Hyperlink/src/hyperlink.scss
> +@import '~@igloo-ui/tokens/dist/base10/variables.css';
doublon

`@import '~@igloo-ui/tokens/dist/base10/variables';` et `@import '~@igloo-ui/tokens/dist/base10/variables.css';`

2022-02-25 14:34 UTC, syvuo approved these changes

2022-02-25 14:49 UTC, ofrogon approved these changes

2022-02-25 17:45 UTC, merged