Chore: standardization of stories
gsoft-inc/ov-igloo-ui pull request #86
Opened 2022-03-11 20:53 UTC by franckgaudin

2022-03-14 16:03 UTC, ofrogon requested changes
Aussi, comme commentaire général, ça pourrait être bien que `xsmall` apparaisse avant `small` et non après `large`.

En cliquant rapidement, je m'attendais à une option `xlarge` après `large` et j'étais surpris d'avoir l'opposé.

![image](https://user-images.githubusercontent.com/4323800/158212267-eba65195-dad3-4de1-b1e2-24da2b213961.png)

2022-03-14 16:03 UTC, ofrogon commented on packages/Tooltip/src/Tooltip.stories.tsx
> +} as ComponentMeta<typeof Tooltip>;
On ne peut presque rien éditer dans le Playground

![image](https://user-images.githubusercontent.com/4323800/158211737-32ab281c-9bf9-40cd-bf79-dac5be71b56a.png)

2022-03-15 00:20 UTC, franckgaudin commented on packages/Card/src/Card.stories.tsx
> +    <Card size="xsmall">Xsmall card</Card>
C'est voulu oui dans certain cas d'utilisation on a simplement besoins de l'effet de la card.

2022-03-15 00:26 UTC, franckgaudin commented on packages/IconButton/src/IconButton.stories.tsx
> +    underline: { table: { defaultValue: { summary: false } } },
bien vue

2022-03-15 13:17 UTC, franckgaudin commented on packages/Toaster/src/Toaster.stories.tsx
> +} as ComponentMeta<typeof Toaster>;
Effectivement, il est différent des autres. Il faudra trouver une solution pour pouvoir l'éditer

2022-03-15 21:41 UTC, ofrogon approved these changes

2022-03-18 14:45 UTC, charlesericjs approved these changes

2022-03-18 15:32 UTC, merged