docs: add search bar for icons
gsoft-inc/ov-igloo-ui pull request #87
Opened 2022-03-16 19:11 UTC by franckgaudin

2022-03-16 21:27 UTC, ofrogon requested changes

2022-03-16 21:27 UTC, ofrogon commented on website/pages/icons.js
> +          Not finding an icon that you want? <a href="#">File an issue</a> and
Si on veut des demandes, on est peut-être mieux de mettre un lien ici.

2022-03-16 21:27 UTC, ofrogon commented on website/pages/icons.js
> +        <Title level={3} as="h4">
Ça je trouve ça étrange comme logique, pourquoi vouloir un `<h3>` qui affiche comme un `<h4>`? Pourquoi pas mettre directement `<h4>` ou avoir le thème du `<h3>` qui ressemble à ce que l'on veut?

\* Je trouve ça juste étrange, mais ce n'est pas une critique.

2022-03-16 21:27 UTC, ofrogon commented on website/styles/variables.scss
> +$c-grey-500: #14171f;
Test nouveaux `c-grey-*` pourraient se retrouver dans la même région que tes anciens `c-grey`, `c-grey-light` et `c-grey-dark`

2022-03-16 21:27 UTC, ofrogon commented on website/styles/variables.scss
>  $c-grey-dark: #cdd9e51a;
On a 2 fois `$c-grey-dark` d'initialisé

2022-03-16 21:29 UTC, ofrogon commented
On a aussi certaines icônes qui n'existent pas en `24` et `36` et qui apparaissent en `Not available`, est-ce que l'on veut qu'ils apparaissent dans la liste des icônes et qu'on puisse également les rechercher?

![image](https://user-images.githubusercontent.com/4323800/158694149-c9e688e0-b15e-4eeb-88b3-407f9a465a0a.png)

2022-03-17 13:35 UTC, franckgaudin commented on netlify.toml
> +  command = "sed -i \"s|HEADER_PLACEHOLDER|${NEXT_PUBLIC_GA_ID}|g\" netlify.toml && yarn doc:build"
En fait cette commande est pour Netlify pour qu'il passe l'ENV a Storybook mais ça ne fonctionne pas.

2022-03-17 13:54 UTC, franckgaudin commented on website/pages/icons.js
> +        <Title level={3} as="h4">
La réflexion en arrière de ça c'est qu'on puisse utiliser des tags sémantiques dans le DOM exemple `<h1> <h2> <h3>` et choisir le rendu visuel dans la page. Car parfois on souhaite avoir un titre un peu plus imposant tout en suivant la structure sémantiques du contenu.

2022-03-17 13:55 UTC, franckgaudin commented on website/styles/variables.scss
> +$c-grey-500: #14171f;
J'ai supprimer les anciennes déclaration de `c-grey`

2022-03-17 15:43 UTC, franckgaudin commented
> On a aussi certaines icônes qui n'existent pas en `24` et `36` et qui apparaissent en `Not available`, est-ce que l'on veut qu'ils apparaissent dans la liste des icônes et qu'on puisse également les rechercher?

On souhaite les afficher oui, ça permet de voir qu'elles n'ont pas été crée dans ces tailles spécifique. Si dans le futur on s'aperçois que nous en avons besoins on fera la demande à l'équipe de Design pour les créer.

2022-03-18 17:38 UTC, syvuo approved these changes

2022-03-18 17:50 UTC, merged