feat(Message): Initial commit
gsoft-inc/ov-igloo-ui pull request #90
Opened 2022-03-22 13:14 UTC by franckgaudin

2022-03-22 14:43 UTC, ofrogon requested changes

2022-03-22 14:43 UTC, ofrogon commented on packages/Message/package.json
> +  "styles": "dist/Message.css",
`message.css` en minuscule

2022-03-22 14:43 UTC, ofrogon commented on packages/Message/src/Message.tsx
> +  appearance?: 'default' | 'warning' | 'error';
Si on veut être constant, on devrait avoir un enum `Appearance`. Comme `Alert`, `Button`, `Hyperlink`, ...

2022-03-22 15:24 UTC, franckgaudin commented on packages/Message/src/Message.tsx
> +  appearance?: 'default' | 'warning' | 'error';
La stratégie a change après discussion avec l'équipe de Design. L'apparence `warning` n'est jamais utilisé.

2022-03-22 19:29 UTC, ofrogon approved these changes

2022-03-24 18:29 UTC, syvuo commented on packages/Kashim/src/Kashim.stories.tsx
> +// export const Appearances = () => (
Commentaires utiles?

2022-03-24 18:34 UTC, franckgaudin commented on packages/Kashim/src/Kashim.stories.tsx
> +// export const Appearances = () => (
Oui c'est pour donner la structure des prochaines stories, ça facilite le copier coller.

2022-03-24 18:42 UTC, syvuo approved these changes

2022-03-24 18:45 UTC, merged