chore: script for bootstraping a component
gsoft-inc/ov-igloo-ui pull request #91
Opened 2022-03-22 17:45 UTC by franckgaudin

2022-03-22 19:06 UTC, ofrogon commented
Ça ne fonctionne pas sur nom poste.

## Lorsque je l'exécute par PowerShell:
![image](https://user-images.githubusercontent.com/4323800/159556126-f1fb424d-8e23-443c-bcdf-cac546420115.png)

Cette erreur n'a pas de sens, car c'est configuré
![image](https://user-images.githubusercontent.com/4323800/159556809-339dba68-5a66-46f2-a413-44cc9606fb98.png)

## Lorsque je l'exécute par `node.exe`:
![image](https://user-images.githubusercontent.com/4323800/159555941-6ea95c2e-72dc-49e2-87f6-26eacbc25e04.png)

2022-03-22 19:12 UTC, ofrogon commented
Pourquoi ne pas utiliser Yeoman pour ça?

https://yeoman.io/

2022-03-22 19:13 UTC, franckgaudin commented
Je ne l'ai pas tester sur PC, visiblement j'ai encore un peu de travail avant qu'on puisse faire passer cette PR :)

2022-03-29 16:01 UTC, ofrogon requested changes
Si tu es capable de faire en sorte de ne pas avoir à utiliser de `.gitkeep` ce serait apprécié, car Git For Windows ne sais pas trop comment réagir avec ce fichier...

2022-04-08 15:47 UTC, ofrogon commented on utils/bootstrap/helpers/index.mjs
> +  return await fs.copy('utils/bootstrap/template', directory);
Super, tu imagine juste pas à quel point mon Git devenait fou avec ce fichier la!

2022-04-08 19:36 UTC, ofrogon approved these changes

2022-04-11 15:31 UTC, charlesericjs approved these changes

2022-04-11 15:32 UTC, merged