feat(radio): Initial commit
gsoft-inc/ov-igloo-ui pull request #92
Opened 2022-03-22 19:15 UTC by franckgaudin

2022-03-22 19:38 UTC, ofrogon commented
Le radio est un peu trop gros, 18x18, alors qu'il devrait être de 16x16

![image](https://user-images.githubusercontent.com/4323800/159561968-ce18c8a4-b4f1-4d72-9135-41be1548a0e7.png)
![image](https://user-images.githubusercontent.com/4323800/159562003-d45a1a4f-3ba3-45ca-82fa-96c93bfaaff4.png)

2022-03-23 15:15 UTC, ofrogon requested changes

2022-03-23 15:15 UTC, ofrogon commented on packages/Radio/src/radio.scss
> +  --ids-radio-background-checked-disabled: #{$grey-400};
`--ids-radio-background-checked-disabled` n'est pas utilisé

2022-03-24 17:00 UTC, franckgaudin commented on packages/Radio/src/Radio.tsx
> +  description?: string;
`message` est utilisé dans le composant `Alert` pour afficher du contenu plus long et ça ne correspond pas a l'utilisation qu'on en fait dans notre cas de figure.  
En regardant les maquettes on peu voir qu'il utilise le terme **helper-text** pour décrire sont utilisation et je pense que c'est plus adapter a notre context.

2022-03-24 17:02 UTC, franckgaudin commented on packages/Radio/src/Radio.test.tsx
> +    expect(radio).toMatchSnapshot();
Tu as raison, l'utilisation du `toMatchSnapshot` ne fonctionne pas dans ce cas, je vais modifier le test pour prendre en compte cette état du composant.

2022-03-24 17:04 UTC, franckgaudin commented on packages/Radio/src/Radio.test.tsx
> +    expect(getByText('Label')).toBeInTheDocument();
C'est ce que fait le test, il valide que le contenu du label est présent dans la page.

2022-03-24 17:37 UTC, ofrogon commented on packages/Radio/src/Radio.test.tsx
> +    expect(getByText('Label')).toBeInTheDocument();
Ha oui, j'avais pas vue

2022-03-24 17:55 UTC, ofrogon commented on packages/Radio/src/Radio.stories.tsx
> +    Small
Ici dans la doc ça peut être trompeur de mettre "small" alors que c'est un label de taille normal,

Aussi j'hésite si "Helper Text" ne serait pas un meilleur contenue de `helperText=` vue que souvent on a tendance à ce que le texte se soit le nom du champ démontré dans l'encadré.

2022-03-24 17:55 UTC, ofrogon commented on packages/Radio/src/Radio.tsx
> +  /** Function called when the value changes. */
Micro commentaire ici. C'est la seule ligne qui se terminer par un point.

2022-03-24 18:52 UTC, syvuo commented on packages/Radio/package.json
> +  "styles": "dist/radio.js",
radio.css

2022-03-24 18:52 UTC, ofrogon submitted a review, later dismissed

2022-03-24 18:59 UTC, syvuo approved these changes

2022-03-24 19:06 UTC, merged